default: &default
  adapter: postgresql
  encoding: unicode
  username: johnvanarkelen
  password:
  pool: 5

development:
  <<: *default
  database: footmarks_development

test:
  <<: *default
  database: footmarks_test
