default: &default
  adapter: postgresql
  encoding: unicode
  username: johnvanarkelen
  password: password1
  template: template0
  host: localhost
  pool: 5

development:
  <<: *default
  database: footmarks_development

test:
  <<: *default
  database: footmarks_test
